### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by yasirrose** [xirdev/xsdk#13]
I have used simplewebrc example and implement it. But i am getting the following error.

xirsys.signal.js:331 Uncaught (in promise) DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at constructor.send (/js/xirsys.signal.js:331:28)
    at constructor.send (/js/xirsys.signal.js:409:15)
    at constructor.emit (/js/xirsys.simplewebrtc.connection.js:94:2

Can any one let me know that what i am doing wrong?

**Comment by Lazarus404** [comment]
This isn't something we can reproduce.  Do you have this hosted somewhere we can see?  Thanks
